[package]
name = "huff"
version = "0.1.0"
authors = ["Dan Muir <daniel.muir.14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
prettytable-rs = "^0.8"

[profile.release]
debug = true
